//
// Copyright (C) 2025 belowzeroiq
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

const translations = {
  en: {
    kernel_profiles_mode: "Kernel Profiles Mode",
    cpu_governor: "CPU Governor",
    thermal_throttling: "Thermal Throttling",
    bypass_charging: "Bypass Charging",
    about_modules: "About Modules",
    kernel_version: "Kernel version",
    device_model: "Device model",
    module_version: "Module version",
    author: "Author",
    github_project: "GitHub Project",
    support_group: "Support group",
    game_bypass: "Auto Bypass for Games",
    game_list: "Game Package List",
    edit: "Edit",
    game_list_help: "Bypass charging will auto-enable when these games are detected",
    edit_game_list: "Edit Game List",
    cancel: "Cancel",
    save: "Save",
    add_game: "Add Game Package",
    package_help: "Enter the game's package name (e.g. com.mobile.legends)",
    add: "Add"
  },
  es: {
    kernel_profiles_mode: "Modo de Perfiles del Kernel",
    cpu_governor: "Gobernador de CPU",
    thermal_throttling: "Limitación Térmica",
    bypass_charging: "Omitir Carga",
    about_modules: "Acerca de los Módulos",
    kernel_version: "Versión del kernel",
    device_model: "Modelo del dispositivo",
    module_version: "Versión del módulo",
    author: "Autor",
    github_project: "Proyecto GitHub",
    support_group: "Grupo de soporte",
    game_bypass: "Bypass automático para juegos",
    game_list: "Lista de paquetes de juegos",
    edit: "Editar",
    game_list_help: "El bypass de carga se activará automáticamente cuando se detecten estos juegos",
    edit_game_list: "Editar lista de juegos",
    cancel: "Cancelar",
    save: "Guardar",
    add_game: "Agregar Paquete de Juego",
    package_help: "Ingrese el nombre del paquete del juego (ej. com.mobile.legends)",
    add: "Agregar"
  },
  id: {
    kernel_profiles_mode: "Mode Profil Kernel",
    cpu_governor: "Governor CPU",
    thermal_throttling: "Pembatasan Termal",
    bypass_charging: "Lewati Pengisian",
    about_modules: "Tentang Modul",
    kernel_version: "Versi kernel",
    device_model: "Model perangkat",
    module_version: "Versi modul",
    author: "Penulis",
    github_project: "Proyek GitHub",
    support_group: "Grup dukungan",
    game_bypass: "Auto Bypass untuk Game",
    game_list: "Daftar Paket Game",
    edit: "Edit",
    game_list_help: "Bypass charging akan aktif otomatis saat game ini terdeteksi",
    edit_game_list: "Edit Daftar Game",
    cancel: "Batal",
    save: "Simpan",
    add_game: "Tambah Paket Game",
    package_help: "Masukkan nama paket game (misal: com.mobile.legends)",
    add: "Tambah"
  },
  ja: {
    kernel_profiles_mode: "カーネルプロファイルモード",
    cpu_governor: "CPUガバナー",
    thermal_throttling: "サーマルスロットリング",
    bypass_charging: "バイパス充電",
    about_modules: "モジュールについて",
    kernel_version: "カーネルバージョン",
    device_model: "デバイスモデル",
    module_version: "モジュールバージョン",
    author: "作者",
    github_project: "GitHubプロジェクト",
    support_group: "サポートグループ",
    game_bypass: "ゲーム自動バイパス",
    game_list: "ゲームパッケージ一覧",
    edit: "編集",
    game_list_help: "これらのゲームが検出されたら自動的にバイパス充電を有効化します",
    edit_game_list: "ゲームリストを編集",
    cancel: "キャンセル",
    save: "保存",
    add_game: "ゲームパッケージを追加",
    package_help: "ゲームのパッケージ名を入力 (例: com.mobile.legends)",
    add: "追加"
  },
  pt: {
    kernel_profiles_mode: "Modo de Perfis do Kernel",
    cpu_governor: "Governador da CPU",
    thermal_throttling: "Limitação Térmica",
    bypass_charging: "Ignorar Carregamento",
    about_modules: "Sobre os Módulos",
    kernel_version: "Versão do kernel",
    device_model: "Modelo do dispositivo",
    module_version: "Versão do módulo",
    author: "Autor",
    github_project: "Projeto no GitHub",
    support_group: "Grupo de suporte",
    game_bypass: "Bypass automático para jogos",
    game_list: "Lista de pacotes de jogos",
    edit: "Editar",
    game_list_help: "O bypass será ativado automaticamente ao detectar esses jogos",
    edit_game_list: "Editar lista de jogos",
    cancel: "Cancelar",
    save: "Salvar",
    add_game: "Adicionar pacote de jogo",
    package_help: "Digite o nome do pacote do jogo (ex: com.mobile.legends)",
    add: "Adicionar"
  },
  zh: {
    kernel_profiles_mode: "内核配置模式",
    cpu_governor: "CPU 调速器",
    thermal_throttling: "温控降频",
    bypass_charging: "旁路充电",
    about_modules: "关于模块",
    kernel_version: "内核版本",
    device_model: "设备型号",
    module_version: "模块版本",
    author: "作者",
    github_project: "GitHub 项目",
    support_group: "支持群组",
    game_bypass: "游戏自动旁路",
    game_list: "游戏包列表",
    edit: "编辑",
    game_list_help: "检测到以下游戏时将自动启用旁路充电",
    edit_game_list: "编辑游戏列表",
    cancel: "取消",
    save: "保存",
    add_game: "添加游戏包",
    package_help: "输入游戏的包名 (例如: com.mobile.legends)",
    add: "添加"
  },
  kr: {
    kernel_profiles_mode: "커널 프로필 모드",
    cpu_governor: "CPU 거버너",
    thermal_throttling: "열 스로틀링",
    bypass_charging: "바이패스 충전",
    about_modules: "모듈 정보",
    kernel_version: "커널 버전",
    device_model: "디바이스 모델",
    module_version: "모듈 버전",
    author: "작성자",
    github_project: "GitHub 프로젝트",
    support_group: "지원 그룹",
    game_bypass: "게임 자동 바이패스",
    game_list: "게임 패키지 목록",
    edit: "편집",
    game_list_help: "다음 게임이 감지되면 자동으로 바이패스 충전이 활성화됩니다",
    edit_game_list: "게임 목록 편집",
    cancel: "취소",
    save: "저장",
    add_game: "게임 패키지 추가",
    package_help: "게임의 패키지 이름 입력 (예: com.mobile.legends)",
    add: "추가"
  }
};